### ISSUE TITLE
any documentation, examples?

### ISSUE THREAD

**Issue by imoad** [subgraph/Orchid#13]
hello, 
any documentation, examples for this lib? i google it nothing found :\

**Comment by hjelperne** [comment]
Any clue as to how to acquire some doc for this would be greatly appreciated!

**Comment by mikehearn** [comment]
The API is quite straightforward. You can look at the source code for bitcoinj to see how to use it. You basically just construct a TorClient() and then use its methods to acquire either a SocketFactory (if you can use that), or start a SOCKS proxy.

If you want to make HTTP requests via Orchid a good way to do this is use OkHTTP rather than the default Java HttpURLConnection API, because OkHTTP lets you specify the socket factory directly. If you want to make HTTPS requests then you can use the standard Java HTTPS stack for that, again, by specifying a SocketFactory directly.

**Comment by instagibbs** [comment]
edit: Nevermind, it's running just fine in my test Java program, so it's somehow more related to bitcoinj. Taking this elsewhere.
